name: Christian Schnieper I Architect
favicon: null
layout_spectrum: 0.25749
typography_spectrum: 1
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Christian Schnieper I Architect
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0603'
    - '#28211b'
    - '#f1e9d4'
    - '#665c52'
    - '#918577'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
