name: Spacecrafter
favicon: null
layout_spectrum: 0.6222976669669151
typography_spectrum: 0.22840247536078095
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6089404034428298
  lightness: 0.08716772752813995
  saturation: 0.8116305533330888
  rhythmicContrast: 0.9438420662190765
purpose: []
